# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AccountManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AccountManager

  pod 'YYModel', '~> 1.0.4'
  pod 'Masonry', '~> 1.1.0'

end
